benchmarks/lobsters/config/routes.rb
# typed: false

Rails.application.routes.draw do
  root to: "home#index",
    # protocol: (Rails.application.config.force_ssl ? "https://" : "http://"),
    as: "root"

  get "/404" => "about#four_oh_four", :via => :all

  get "/rss" => "home#index", :format => "rss"
  get "/hottest" => "home#index", :format => "json"

  get "/page/:page" => "home#index"

  get "/active" => "home#active"
  get "/active/page/:page" => "home#active"
  get "/newest" => "home#newest"
  get "/newest/page/:page" => "home#newest"
  get "/recent" => "home#recent"
  get "/recent/page/:page" => "home#recent"
  get "/hidden" => "home#hidden"
  get "/hidden/page/:page" => "home#hidden"

  get "/saved" => "home#saved"
  get "/saved/page/:page" => "home#saved"
  get "/upvoted/stories" => "home#upvoted"
  get "/upvoted/stories/page/:page" => "home#upvoted"
  get "/upvoted/comments" => "comments#upvoted"
  get "/upvoted/comments/page/:page" => "comments#upvoted"
  get "/upvoted", to: redirect("/upvoted/stories")
  get "/upvoted/page/:page", to: redirect("/upvoted/stories/page/%{page}")

  get "/top" => "home#top"
  get "/top/rss" => "home#top", :format => "rss"
  get "/top/page/:page" => "home#top"
  get "/top/:length" => "home#top"
  get "/top/:length/page/:page" => "home#top"

  get "/threads" => "comments#user_threads"

  get "/replies" => "replies#all"
  get "/replies/page/:page" => "replies#all"
  get "/replies/comments" => "replies#comments"
  get "/replies/comments/page/:page" => "replies#comments"
  get "/replies/stories" => "replies#stories"
  get "/replies/stories/page/:page" => "replies#stories"
  get "/replies/unread" => "replies#unread"
  get "/replies/unread/page/:page" => "replies#unread"

  get "/login" => "login#index"
  post "/login" => "login#login"
  post "/logout" => "login#logout"
  get "/login/2fa" => "login#twofa"
  post "/login/2fa_verify" => "login#twofa_verify", :as => "twofa_login"

  get "/signup" => "signup#index"
  post "/signup" => "signup#signup"
  get "/signup/invite" => "signup#invite"

  get "/login/forgot_password" => "login#forgot_password",
    :as => "forgot_password"
  post "/login/reset_password" => "login#reset_password",
    :as => "reset_password"
  match "/login/set_new_password" => "login#set_new_password",
    :as => "set_new_password", :via => [:get, :post]

  get "/t/:tag" => "home#single_tag", :as => "tag", :constraints => {tag: /[^,\.]+/}
  get "/t/:tag" => "home#multi_tag", :as => "multi_tag"
  get "/t/:tag/page/:page" => "home#tagged"

  constraints id: /([^\/]+?)(?=\.json|\.rss|$|\/)/ do
    get "/domain/:id(.:format)", to: redirect("/domains/%{id}")
    get "/domain/:id/page/:page", to: redirect("/domains/%{id}/page/%{page}")
    get "/domains/:id(.:format)" => "home#for_domain", :as => "domain"
    get "/domains/:id/page/:page" => "home#for_domain"
    get "/domains/:id/origins" => "origins#for_domain", :as => "domain_origins"

    resources :domains, only: [:create, :edit, :update]
    patch "/domains_ban/:id" => "domains_ban#update", :as => "ban_domain"
    post "/domains_ban/:id" => "domains_ban#create_and_ban", :as => "create_and_ban_domain"

    # below `resources` so that /edit isn't taken as an identifier
    get "/domains/:id/:author", to: redirect("/origins/%{id}/%{author}")
    get "/domain/:domain/:identifier(.:format)", to: redirect("/domains/%{domain}/%{identifier}")
    get "/domain/:domain/:identifier/page/:page", to: redirect("/domains/%{domain}/%{idetifier}/page/%{page}")
  end

  constraints identifier: /(.+)(?=\.json|\.rss|$|\/)/ do
    # resources :origin, only: [:show, :edit, :update]
    get "/origins/:identifier/edit(.:format)" => "origins#edit", :as => "edit_origin"
    patch "/origins/:identifier" => "origins#update", :as => "update_origin"
    get "/origins/:identifier(.:format)" => "home#for_origin", :as => "origin"
    # leaving out pagination because identifiers (eg 'github.com/alice') can include slashes
    # get "/origins/:identifier/page/:page" => "home#for_domain"
  end

  get "/search" => "search#index"
  get "/search/:q" => "search#index"

  get "/stories/url/all" => "story_urls#all"
  get "/stories/url/latest" => "story_urls#latest"

  resources :stories, except: [:index] do
    get "/stories/:short_id", to: redirect("/s/%{short_id}")
    post "upvote"
    post "flag"
    post "unvote"
    patch "destroy"
    patch "undelete"
    post "hide"
    post "unhide"
    post "save"
    post "unsave"
    post "disown"
    resources :suggestions, only: [:new, :create]

    # Mapping old routes to new routes. can be safely removed after the next deployment
    get "suggest", to: redirect("/stories/suggestions/new", status: 302)
    post "suggest", to: redirect("/stories/suggestions", status: 307)
  end
  post "/stories/fetch_url_attributes", format: "json"
  post "/stories/preview" => "stories#preview"
  post "/stories/check_url_dupe" => "stories#check_url_dupe"

  resources :comments, except: [:new, :destroy] do
    member do
      get "/comments/:id" => "comments#redirect_from_short_id"
      get "reply"
      post "upvote"
      post "flag"
      post "unvote"

      post "delete"
      post "undelete"
      post "disown"
    end
  end
  get "/comments/page/:page" => "comments#index"
  get "/comments" => "comments#index"

  get "/messages/sent" => "messages#sent"
  get "/messages" => "messages#index"
  post "/messages/batch_delete" => "messages#batch_delete",
    :as => "batch_delete_messages"
  resources :messages do
    post "keep_as_new"
    post "mod_note"
  end

  get "/inbox" => "inbox#index"

  get "/c/:id.json" => "comments#show_short_id", :format => "json"
  get "/c/:id" => "comments#redirect_from_short_id"

  # deprecated
  get "/s/:story_id/:title/comments/:id" => "comments#redirect_from_short_id"

  get "/s/:id/(:title)" => "stories#show"

  get "/users" => "users#tree", :as => "users_tree"
  get "/~:username" => "users#show", :as => "user"
  get "/~:username/standing" => "users#standing", :as => "user_standing"
  get "/~:user/stories(/page/:page)" => "home#newest_by_user", :as => "newest_by_user"
  get "/~:user/threads" => "comments#user_threads", :as => "user_threads"

  post "/~:username/ban" => "users#ban", :as => "user_ban"
  post "/~:username/unban" => "users#unban", :as => "user_unban"
  post "/~:username/disable_invitation" => "users#disable_invitation",
    :as => "user_disable_invite"
  post "/~:username/enable_invitation" => "users#enable_invitation",
    :as => "user_enable_invite"

  # 2023-07 redirect /u to /~username and /users (for tree)
  get "/u", to: redirect("/users", status: 301)
  get "/u/:username", to: redirect("/~%{username}", status: 301)
  # we don't do /@alice but easy mistake with comments autolinking @alice
  get "/@:username", to: redirect("/~%{username}", status: 301)
  get "/u/:username/standing", to: redirect("~%{username}/standing", status: 301)
  get "/newest/:user", to: redirect("~%{user}/stories", status: 301)
  get "/newest/:user(/page/:page)", to: redirect("~%{user}/stories/page/%{page}", status: 301)
  get "/threads/:user", to: redirect("~%{user}/threads", status: 301)

  get "/avatars/:username_size.png" => "avatars#show"
  post "/avatars/expire" => "avatars#expire"

  get "/settings" => "settings#index"
  post "/settings" => "settings#update"
  post "/settings/delete_account" => "settings#delete_account",
    :as => "delete_account"
  get "/settings/2fa" => "settings#twofa", :as => "twofa"
  post "/settings/2fa_auth" => "settings#twofa_auth", :as => "twofa_auth"
  get "/settings/2fa_enroll" => "settings#twofa_enroll",
    :as => "twofa_enroll"
  get "/settings/2fa_verify" => "settings#twofa_verify",
    :as => "twofa_verify"
  post "/settings/2fa_update" => "settings#twofa_update",
    :as => "twofa_update"
  post "/settings/pushover_auth" => "settings#pushover_auth"
  get "/settings/pushover_callback" => "settings#pushover_callback"
  get "/settings/mastodon_authentication" => "settings#mastodon_authentication"
  get "/settings/mastodon_auth" => "settings#mastodon_auth"
  get "/settings/mastodon_callback" => "settings#mastodon_callback"
  post "/settings/mastodon_disconnect" => "settings#mastodon_disconnect"
  get "/settings/github_auth" => "settings#github_auth"
  get "/settings/github_callback" => "settings#github_callback"
  post "/settings/github_disconnect" => "settings#github_disconnect"

  resources :keybase_proofs, only: [:new, :create, :destroy]
  get "/.well-known/keybase-proof-config" => "keybase_proofs#kbconfig", :as => "keybase_config"

  get "/filters" => "filters#index"
  post "/filters" => "filters#update"

  get "/tags" => "tags#index"
  get "/tags.json" => "tags#index", :format => "json"
  get "/tags/new" => "tags#new", :as => "new_tag"
  get "/tags/:tag_name/edit" => "tags#edit", :as => "edit_tag"
  post "/tags" => "tags#create"
  post "/tags/:tag_name" => "tags#update", :as => "update_tag"

  get "/categories/new" => "categories#new", :as => "new_category"
  get "/categories/:category_name/edit" => "categories#edit", :as => "edit_category"
  get "/categories/:category" => "home#category", :as => :category
  post "/categories" => "categories#create"
  post "/categories/:category_name" => "categories#update", :as => "update_category"

  post "/invitations" => "invitations#create"
  get "/invitations" => "invitations#index"
  get "/invitations/request" => "invitations#build"
  post "/invitations/create_by_request" => "invitations#create_by_request",
    :as => "create_invitation_by_request"
  get "/invitations/confirm/:code" => "invitations#confirm_email"
  post "/invitations/send_for_request" => "invitations#send_for_request",
    :as => "send_invitation_for_request"
  get "/invitations/:invitation_code" => "signup#invited"
  post "/invitations/delete_request" => "invitations#delete_request",
    :as => "delete_invitation_request"

  resources :hat_requests, except: [:edit] do
    member do
      post :approve
      post :reject
    end
  end

benchmarks/lobsters/app/controllers/users_controller.rb
# typed: false

class UsersController < ApplicationController
  before_action :load_showing_user, only: [:show, :standing]
  before_action :require_logged_in_admin,
    only: [:enable_invitation, :disable_invitation, :ban, :unban]
  before_action :require_logged_in_user, only: [:standing]
  before_action :only_user_or_moderator, only: [:standing]
  before_action :show_title_h1, only: [:show]

  def show
    @title = @showing_user.username
    if @showing_user.is_active?
      @title_class = :inactive_user
    elsif @showing_user.is_new?
      @title_class = :new_user
    end

    if @user.try(:is_moderator?)
      @mod_note = ModNote.new(user: @showing_user)
      @mod_note.note = params[:note]
    end

    respond_to do |format|
      format.html { render action: "show" }
      format.json { render json: @showing_user }
    end
  end

  def tree
    @title = "Users"
    newest_user = User.last.id

    # pulling 10k+ users is significant enough memory pressure this is worthwhile
    attrs = %w[banned_at created_at deleted_at id invited_by_user_id is_admin is_moderator karma
      username]

    if params[:by].to_s == "karma"
      content = Rails.cache.fetch("users_by_karma_#{newest_user}", expires_in: (60 * 60 * 24)) {
        @users = User.select(*attrs).order("karma DESC, id ASC").to_a
        @user_count = @users.length
        @title << " By Karma"
        render_to_string action: "list", layout: nil
      }
      render html: content.html_safe, layout: "application"
    elsif params[:moderators]
      @users = User.select(*attrs).where("is_admin = ? OR is_moderator = ?", true, true)
        .order("id ASC").to_a
      @user_count = @users.length
      @title = "Moderators and Administrators"
      render action: "list"
    else
      # Mod::ReparentsController#create knows this key
      content = Rails.cache.fetch("users_tree_#{newest_user}", expires_in: 12.hours) {
        users = User.select(*attrs).order("id DESC").to_a
        @user_count = users.length
        @users_by_parent = users.group_by(&:invited_by_user_id)
        @newest = User.select(*attrs).order("id DESC").limit(10)
        render_to_string action: "tree", layout: nil
      }
      render html: content.html_safe, layout: "application"
    end
  end

  def disable_invitation
    target = User.where(username: params[:username]).first
    if !target
      flash[:error] = "Invalid user."
      redirect_to "/"
    else
      target.disable_invite_by_user_for_reason!(@user, params[:reason])

      flash[:success] = "User has had invite capability disabled."
      redirect_to user_path(user: target.username)
    end
  end

  def enable_invitation
    target = User.where(username: params[:username]).first
    if !target
      flash[:error] = "Invalid user."
      redirect_to "/"
    else
      target.enable_invite_by_user!(@user)

      flash[:success] = "User has had invite capability enabled."
      redirect_to user_path(user: target.username)
    end
  end

  def ban
    buser = User.where(username: params[:username]).first
    if !buser
      flash[:error] = "Invalid user."
      return redirect_to "/"
    end

    if params[:reason].blank?
      flash[:error] = "You must give a reason for the ban."
      return redirect_to user_path(user: buser.username)
    end

    buser.ban_by_user_for_reason!(@user, params[:reason])

    flash[:success] = "User has been banned."
    redirect_to user_path(user: buser.username)
  end

  def unban
    buser = User.where(username: params[:username]).first
    if !buser
      flash[:error] = "Invalid user."
      return redirect_to "/"
    end

    buser.unban_by_user!(@user, params[:reason])

    flash[:success] = "User has been unbanned."
    redirect_to user_path(user: buser.username)
  end

  def standing
    @interval = time_interval("1m")

    fc = FlaggedCommenters.new(@interval[:param], 1.day)
    @fc_flagged = fc.commenters.map { |_, c| c[:n_flags] }.sort
    @flagged_user_stats = fc.check_list_for(@showing_user)

    rows = ActiveRecord::Base.connection.exec_query("
      select
        n_flags, count(*) as n_users
      from (
        select
          comments.user_id, sum(flags) as n_flags
        from
          comments
        where
          comments.created_at >= now() - interval #{@interval[:dur]} #{@interval[:intv]}
        group by comments.user_id) count_by_user
      group by 1
      order by 1 asc;
    ").rows
    users = Array.new(@fc_flagged.last.to_i + 1, 0)
    rows.each { |r| users[r.first] = r.last }
    @lookup = rows.to_h

    @flagged_comments = @showing_user.comments
      .where("
        comments.flags > 0 and
        comments.created_at >= now() - interval #{@interval[:dur]} #{@interval[:intv]}")
      .order("id DESC")
      .includes(:user, :hat, story: :user)
      .joins(:story)
  end

  private

  def load_showing_user
    # case-insensitive search by username
    @showing_user = User.find_by(username: params[:username])

    if @showing_user.nil?
      @title = "User not found"
      render action: :not_found, status: 404
      return false
    end

    # now a case-sensitive check
    if params[:username] != @showing_user.username
      redirect_to username: @showing_user.username
      false
    end
  end

  def only_user_or_moderator
    if params[:username] == @user.username || @user.is_moderator?
      true
    else
      redirect_to(user_path(params[:username]))
    end
  end
end

benchmarks/lobsters/app/helpers/users_helper.rb
# typed: false

module UsersHelper
  def self_or_mod(showing_user, user)
    user == showing_user || user.try(:is_moderator?)
  end

  def stories_submitted_content(user, showing_user)
    tag = showing_user.most_common_story_tag

    stories_submitted = showing_user.stories_submitted_count
    stories_deleted = showing_user.stories_deleted_count
    stories_displayed = stories_submitted - stories_deleted

    capture do
      concat link_to(stories_displayed, newest_by_user_path(showing_user))

      concat(" (+#{stories_deleted} deleted)") if user&.is_moderator? && stories_deleted > 0

      if tag
        concat ", most commonly tagged "
        concat link_to(tag.tag, tag_path(tag), class: tag.css_class, title: tag.description)
      end
    end
  end

  def comments_posted_content(user, showing_user)
    comments_deleted = showing_user.comments_deleted_count

    capture do
      concat link_to(showing_user.comments_posted_count, user_threads_path(showing_user))

      if user&.is_moderator? && comments_deleted > 0
        concat " (+#{comments_deleted} deleted)"
      end
    end
  end

  def styled_user_link user, content = nil, html_options = {}
    html_options[:class] ||= []
    if content.is_a?(Story) && content.user_is_author?
      html_options[:class].push "user_is_author"
    end
    if content.is_a?(Comment) && content.story&.user_is_author? && content.story.user_id == user.id
      html_options[:class].push "user_is_author"
    end

    if !user.is_active?
      html_options[:class].push "inactive_user"
    end
    if user.is_new?
      html_options[:class].push "new_user"
    end
    html_options.delete(:class) if html_options[:class].empty?

    link_to(user.username, user, html_options)
  end

  def user_karma(user)
    if user.is_admin?
      "(administrator)"
    elsif user.is_moderator?
      "(moderator)"
    else
      "(#{user.karma})"
    end
  end
end

benchmarks/lobsters/app/views/users/_dev_flag_warning.html.erb
<div class="flash-notice">
  Skipped slow queries for flag warning in mode <tt><%= Rails.env %></tt>.
</div>

benchmarks/lobsters/app/views/users/list.html.erb
<div class="box wide">
  <p>
  <strong><%= @title %> (<%= @user_count %>)</strong>
  </p>

  <ul class="user_tree">
  <% @users.each do |user| %>
    <li>
      <%= styled_user_link(user) %>
      <%= user_karma(user) %>
    </li>
  <% end %>
  </ul>
</div>

benchmarks/lobsters/app/views/users/show.html.erb
<%= possible_flag_warning(@showing_user, @user) %>

<% content_for :subnav do %>
  <% if @user && @showing_user.is_active? && @showing_user != @user %>
    <a href="/messages?to=<%= @showing_user.username %>">Send a Message</a>
  <% end %>
<% end %>

<div class="box wide">
  <% if @showing_user.is_active? %>
    <div id="gravatar">
      <%= avatar_img(@showing_user, 100) %>
    </div>
  <% end %>

  <label class="required">Status:</label>
  <span class="d"
  <%= @showing_user.is_banned? ? raw("style=\"color: red;\"") : "" %>>
    <% if @showing_user.is_banned? %>
      Banned user
    <% elsif !@showing_user.is_active? %>
      Inactive user
    <% else %>
      Active
      <%= @showing_user.is_admin? ? "administrator" :
        (@showing_user.is_moderator? ? "moderator" : "user") %>
      <% if !@showing_user.can_invite? %>
        with invites
        <% if !@showing_user.can_submit_stories? %>
          and story submissions
        <% end %>
        disabled
      <% end %>
    <% end %>
  </span>
  <br>

  <label class="required">Joined:</label>
  <span class="d">
    <%= how_long_ago_label(@showing_user.created_at) %>
    <% if @showing_user.invited_by_user %>
      by <%= link_to 'invitation', users_tree_path(anchor: @showing_user.username) %> from
      <%= link_to @showing_user.invited_by_user.try(:username), @showing_user.invited_by_user %>
    <% end %>
  </span>
  <br>

  <% if @showing_user.is_banned? %>
    <label class="required">Banned:</label>
    <span class="d">
      <%= how_long_ago_label(@showing_user.banned_at) %>
      <% if @showing_user.banned_by_user %>
        by <%= link_to @showing_user.banned_by_user.try(:username),
          @showing_user.banned_by_user %>:
          <em><%= @showing_user.banned_reason %></em>
      <% end %>
    </span>
    <br>
  <% end %>

  <% if @showing_user.deleted_at? %>
    <label class="required">Left:</label>
    <span class="d">
      <%= how_long_ago_label(@showing_user.deleted_at) %>
    </span>
    <br>
  <% end %>

  <% if !@showing_user.is_admin? %>
    <label class="required">Karma:</label>
    <span class="d">
      <%= @showing_user.karma %>
    </span>
    <br>
  <% end %>

  <label class="required">Stories Submitted:</label>
  <span class="d">
    <%= stories_submitted_content(@user, @showing_user) %>
  </span>
  <br>

  <label class="required">Comments Posted:</label>
  <span class="d"><%= comments_posted_content(@user, @showing_user) %></span>
  <br>

  <% if @showing_user.hats.any? %>
    <label class="required">Hats:</label>
    <div class="d">
    <% @showing_user.hats.each do |hat| %>
      <%= hat.to_html_label %>
      <% if hat.doffed_at? %>
        doffed <%= how_long_ago_label(hat.doffed_at) %>
      <% else %>
        <% if @user && ((hat.user == @user) || @user.is_moderator?) %>
          <%= link_to 'Doff', doff_hat_path(hat) %>
        <% end %>
      <% end %>
      <br>
    <% end %>
    </div>
    <div style="clear: both;"></div>
  <% end %>

  <% if @user&.is_admin? || @user&.show_email? %>
    <label class="required">E-Mail:</label>
    <span class="d">
      <%= @showing_user.email %>
    </span>
    <br>
  <% end %>

  <% if @showing_user.homepage.present? %>
    <label class="required">Homepage:</label>

    <span class="d">
      <a href="<%= h(@showing_user.homepage) %>"
        rel="me ugc"><%= h(@showing_user.homepage) %></a>
      <% if @showing_user.homepage.start_with?('gemini://') %>
        (<a href="https://portal.mozz.us/gemini/<% h(@showing_user.homepage[9..-1]) %>">proxy</a>)
      <% elsif @showing_user.homepage.start_with?('gopher://') %>
        (<a href="https://gopher.floodgap.com/gopher/gw?<% h(@showing_user.homepage[9..-1]) %>">proxy</a>)
      <% end %>
    </span>
    <br>
  <% end %>

  <% if @showing_user.github_username.present? %>
    <label class="required">GitHub:</label>

    <span class="d">
      <a href="https://github.com/<%= h(@showing_user.github_username) %>"
        rel="me ugc">https://github.com/<%= h(@showing_user.github_username)
        %></a>
    </span>
    <br>
  <% end %>

  <% if @showing_user.mastodon_username.present? && @showing_user.mastodon_instance.present? %>
    <label class="required">Mastodon:</label>

    <span class="d">
      <a href="https://<%= h(@showing_user.mastodon_instance)%>/@<%= h(@showing_user.mastodon_username)%>"
        rel="me ugc">@<%= h(@showing_user.mastodon_username)%>@<%= h(@showing_user.mastodon_instance)%>
        </a>
    </span>
    <br>
  <% end %>

  <% if Keybase.enabled? && @showing_user.keybase_signatures? %>
    <label class="required">Keybase:</label>
    <span class="d">
      <%= render :partial => "keybase_proofs/proofs", locals: { user: @showing_user, for_self: false } %>
    </span>
    <br>
  <% end %>

  <% if @showing_user.is_active? %>
    <label class="required">About:</label>

    <div class="d shorten_first_p">
      <% if @showing_user.about.present? %>
        <%= raw @showing_user.linkified_about %>
      <% else %>
        <span class="na">A mystery...</span>
      <% end %>
      <br>
    </div>
  <% end %>

  <% if Rails.env.development? || @user == @showing_user || @user&.is_moderator? %>
    <div class="user-stats flash-notice">
      <p>
        Comments posted in the last 6 months: <%= @showing_user.comments.recent.count %><br>
        &nbsp;&nbsp;...posted on stories you didn't author: <%= @showing_user.comments.recent.on_stories_not_authored_by(@showing_user).count %><br>
        &nbsp;&nbsp;&nbsp;&nbsp;...received above average score: <%= @showing_user.comments.recent.on_stories_not_authored_by(@showing_user).above_average.count %>
      </p>

      <p>(This section is only visible to you and moderators.
      Mods use it when evaluating whether 
      users are participating in the community or exploiting the site for <a href="/about#self-promo">self-promo</a>. It's a red flag when someone never posts well-received comments outside of their own links.)
    </div>
  <% end %>

  <% if @user && @user.is_moderator? && !@showing_user.is_moderator? %>
    <h2>Moderator Information</h2>

    <label class="required">Flagged (1m):</label>
    <span class="d">
      <% if (stats = FlaggedCommenters.new('1m').check_list_for(@showing_user)) %>
        <a href="/mod/commenters/1m#<%= @showing_user.username %>">#<%= stats[:rank] %></a> at <%= '%.2f' % (stats[:sigma] || 0) %> &sigma;
      <% else %>
        No
      <% end %>
    </span>
    <br>

    <label class="required">Self Promoter:</label>
    <span class="d">
      <% if @showing_user.is_heavy_self_promoter? %>
        <strong>Yes</strong>
      <% else %>
        No
      <% end %>
    </span>
    <br>

    <label class="required">Last 10 Notes:</label>
    <%= render partial: 'mod_notes/table', locals: {
      mod_notes: ModNote.for(@showing_user).limit(10),
    } %>
    <%= form_with model: @mod_note, method: :post do |f| %>
      <%= errors_for @mod_note %>
      <%= f.hidden_field :username %>
      <div class="boxline">
        <%= f.label :note, "New Note:", :class => "required" %>
        <%= f.text_area :note, :style => "width: 500px;", :rows => 5 %>
      </div>
      <div class="boxline"><p></p><%= f.submit "ModNote" %></div>
    <% end %>

    <label class="required">Latest modlog for this user:</label>
    <%= render partial: 'moderations/table', locals: { moderations: Moderation.for_user(@showing_user) } %>


    <% if @user.is_admin? %>
      <h3>Admin Information</h3>

      <label class="required">Recent Votes:</label>
      <table class="data zebra clear tall">
        <% @showing_user.votes_for_others.limit(15).each do |v| %><tr>
          <td><%= v.vote == 1 ? '+' : v.reason %></td>
          <% if v.comment_id %>
            <td><a href="/~<%= v.comment.user.try(:username) %>"><%= v.comment.user.try(:username) %></a></td>
            <td>
              <%= v.story.title %>
              <a href="<%= v.comment.short_id_url %>">comment</a>:<br>
              <%= v.comment.comment.split[0..10].join(' ') %>
            </td>
          <% elsif v.story_id && !v.comment_id %>
            <td><a href="/~<%= v.story.user.try(:username) %>"><%= v.story.user.try(:username) %></a></td>
            <td><a href="<%= v.story.short_id_url %>"><%= v.story.title %></a></td>
          <% end %>
          </p>
        </tr><% end %>
      </table>

      <% if @showing_user.is_banned? || @showing_user.banned_from_inviting? %>
        <%= form_with url: user_unban_path, method: :post do |f| %>
          <p>
            <% if @showing_user.is_banned? %>
              <div class="boxline">
                <%= f.label :reason, "Reason:", :class => "required" %>
                <%= f.text_field :reason, :size => 80 %>
              </div>
              <%= f.submit "Unban" %>
            <% end %>
            <% if @showing_user.banned_from_inviting? %>
              <%= f.submit "Enable Invites", formaction: user_enable_invite_path %>
            <% end %>
          </p>
        <% end %>
      <% end %>

      <% if !@showing_user.is_banned? || !@showing_user.banned_from_inviting? %>
        <p>
          Banning or disabling invites for a user will send an e-mail to the user with the reason below,
          with your e-mail address as the Reply-To so the user can respond.
        </p>
        <%= form_with url: user_ban_path, method: :post do |f| %>
          <div class="boxline">
            <%= f.label :reason, "Reason:", :class => "required" %>
            <%= f.text_field :reason, :size => 80 %>
          </div>
          <p>
            <% if !@showing_user.is_banned? %>
              <%= f.submit "Ban", class: 'deletion' %>
            <% end %>
            <% if !@showing_user.banned_from_inviting? %>
              <%= f.submit "Disable Invites", formaction: user_disable_invite_path %>
            <% end %>
          </p>
        <% end %>
      <% end %>

      <%= link_to 'Reparent', new_mod_reparent_path({}, id: @showing_user) %>
    <% end %>
  <% end %>
</div>