benchmarks/lobsters/config/routes.rb
  get "/top/rss" => "home#top", :format => "rss"
  get "/top/page/:page" => "home#top"
  get "/top/:length" => "home#top"
  get "/top/:length/page/:page" => "home#top"

  get "/threads" => "comments#user_threads"

  get "/replies" => "replies#all"
  get "/replies/page/:page" => "replies#all"
  get "/replies/comments" => "replies#comments"
  get "/replies/comments/page/:page" => "replies#comments"
  get "/replies/stories" => "replies#stories"
  get "/replies/stories/page/:page" => "replies#stories"
  get "/replies/unread" => "replies#unread"
  get "/replies/unread/page/:page" => "replies#unread"

  get "/login" => "login#index"
  post "/login" => "login#login"
  post "/logout" => "login#logout"
  get "/login/2fa" => "login#twofa"
  post "/login/2fa_verify" => "login#twofa_verify", :as => "twofa_login"

  get "/signup" => "signup#index"
  post "/signup" => "signup#signup"
  get "/signup/invite" => "signup#invite"

  get "/login/forgot_password" => "login#forgot_password",
    :as => "forgot_password"
  post "/login/reset_password" => "login#reset_password",
    :as => "reset_password"
  match "/login/set_new_password" => "login#set_new_password",
    :as => "set_new_password", :via => [:get, :post]

  get "/t/:tag" => "home#single_tag", :as => "tag", :constraints => {tag: /[^,\.]+/}
  get "/t/:tag" => "home#multi_tag", :as => "multi_tag"
  get "/t/:tag/page/:page" => "home#tagged"

  constraints id: /([^\/]+?)(?=\.json|\.rss|$|\/)/ do
    get "/domain/:id(.:format)", to: redirect("/domains/%{id}")
    get "/domain/:id/page/:page", to: redirect("/domains/%{id}/page/%{page}")
    get "/domains/:id(.:format)" => "home#for_domain", :as => "domain"
    get "/domains/:id/page/:page" => "home#for_domain"
    get "/domains/:id/origins" => "origins#for_domain", :as => "domain_origins"

    resources :domains, only: [:create, :edit, :update]
    patch "/domains_ban/:id" => "domains_ban#update", :as => "ban_domain"
    post "/domains_ban/:id" => "domains_ban#create_and_ban", :as => "create_and_ban_domain"

    # below `resources` so that /edit isn't taken as an identifier
    get "/domains/:id/:author", to: redirect("/origins/%{id}/%{author}")
    get "/domain/:domain/:identifier(.:format)", to: redirect("/domains/%{domain}/%{identifier}")
    get "/domain/:domain/:identifier/page/:page", to: redirect("/domains/%{domain}/%{idetifier}/page/%{page}")
  end

  constraints identifier: /(.+)(?=\.json|\.rss|$|\/)/ do
    # resources :origin, only: [:show, :edit, :update]
    get "/origins/:identifier/edit(.:format)" => "origins#edit", :as => "edit_origin"
    patch "/origins/:identifier" => "origins#update", :as => "update_origin"
    get "/origins/:identifier(.:format)" => "home#for_origin", :as => "origin"
    # leaving out pagination because identifiers (eg 'github.com/alice') can include slashes
    # get "/origins/:identifier/page/:page" => "home#for_domain"
  end

  get "/search" => "search#index"
  get "/search/:q" => "search#index"

  get "/stories/url/all" => "story_urls#all"
  get "/stories/url/latest" => "story_urls#latest"

  resources :stories, except: [:index] do
    get "/stories/:short_id", to: redirect("/s/%{short_id}")
    post "upvote"
    post "flag"
    post "unvote"
    patch "destroy"
    patch "undelete"
    post "hide"
    post "unhide"
    post "save"
    post "unsave"
    post "disown"
    resources :suggestions, only: [:new, :create]

    # Mapping old routes to new routes. can be safely removed after the next deployment
    get "suggest", to: redirect("/stories/suggestions/new", status: 302)
    post "suggest", to: redirect("/stories/suggestions", status: 307)
  end
  post "/stories/fetch_url_attributes", format: "json"
  post "/stories/preview" => "stories#preview"
  post "/stories/check_url_dupe" => "stories#check_url_dupe"

  resources :comments, except: [:new, :destroy] do
    member do
      get "/comments/:id" => "comments#redirect_from_short_id"
      get "reply"
      post "upvote"
      post "flag"
      post "unvote"

      post "delete"
      post "undelete"
      post "disown"
    end
  end
  get "/comments/page/:page" => "comments#index"
  get "/comments" => "comments#index"

  get "/messages/sent" => "messages#sent"
  get "/messages" => "messages#index"
  post "/messages/batch_delete" => "messages#batch_delete",
    :as => "batch_delete_messages"
  resources :messages do
    post "keep_as_new"
    post "mod_note"
  end

  get "/inbox" => "inbox#index"

  get "/c/:id.json" => "comments#show_short_id", :format => "json"
  get "/c/:id" => "comments#redirect_from_short_id"

  # deprecated
  get "/s/:story_id/:title/comments/:id" => "comments#redirect_from_short_id"

  get "/s/:id/(:title)" => "stories#show"

  get "/users" => "users#tree", :as => "users_tree"
  get "/~:username" => "users#show", :as => "user"
  get "/~:username/standing" => "users#standing", :as => "user_standing"
  get "/~:user/stories(/page/:page)" => "home#newest_by_user", :as => "newest_by_user"
  get "/~:user/threads" => "comments#user_threads", :as => "user_threads"

  post "/~:username/ban" => "users#ban", :as => "user_ban"
  post "/~:username/unban" => "users#unban", :as => "user_unban"
  post "/~:username/disable_invitation" => "users#disable_invitation",
    :as => "user_disable_invite"
  post "/~:username/enable_invitation" => "users#enable_invitation",
    :as => "user_enable_invite"

  # 2023-07 redirect /u to /~username and /users (for tree)
  get "/u", to: redirect("/users", status: 301)
  get "/u/:username", to: redirect("/~%{username}", status: 301)
  # we don't do /@alice but easy mistake with comments autolinking @alice
  get "/@:username", to: redirect("/~%{username}", status: 301)
  get "/u/:username/standing", to: redirect("~%{username}/standing", status: 301)
  get "/newest/:user", to: redirect("~%{user}/stories", status: 301)
  get "/newest/:user(/page/:page)", to: redirect("~%{user}/stories/page/%{page}", status: 301)
  get "/threads/:user", to: redirect("~%{user}/threads", status: 301)

  get "/avatars/:username_size.png" => "avatars#show"
  post "/avatars/expire" => "avatars#expire"

  get "/settings" => "settings#index"
  post "/settings" => "settings#update"
  post "/settings/delete_account" => "settings#delete_account",
    :as => "delete_account"
  get "/settings/2fa" => "settings#twofa", :as => "twofa"
  post "/settings/2fa_auth" => "settings#twofa_auth", :as => "twofa_auth"
  get "/settings/2fa_enroll" => "settings#twofa_enroll",
    :as => "twofa_enroll"
  get "/settings/2fa_verify" => "settings#twofa_verify",
    :as => "twofa_verify"
  post "/settings/2fa_update" => "settings#twofa_update",
    :as => "twofa_update"
  post "/settings/pushover_auth" => "settings#pushover_auth"
  get "/settings/pushover_callback" => "settings#pushover_callback"
  get "/settings/mastodon_authentication" => "settings#mastodon_authentication"
  get "/settings/mastodon_auth" => "settings#mastodon_auth"
  get "/settings/mastodon_callback" => "settings#mastodon_callback"
  post "/settings/mastodon_disconnect" => "settings#mastodon_disconnect"
  get "/settings/github_auth" => "settings#github_auth"
  get "/settings/github_callback" => "settings#github_callback"
  post "/settings/github_disconnect" => "settings#github_disconnect"

  resources :keybase_proofs, only: [:new, :create, :destroy]
  get "/.well-known/keybase-proof-config" => "keybase_proofs#kbconfig", :as => "keybase_config"

  get "/filters" => "filters#index"
  post "/filters" => "filters#update"

  get "/tags" => "tags#index"
  get "/tags.json" => "tags#index", :format => "json"
  get "/tags/new" => "tags#new", :as => "new_tag"
  get "/tags/:tag_name/edit" => "tags#edit", :as => "edit_tag"
  post "/tags" => "tags#create"
  post "/tags/:tag_name" => "tags#update", :as => "update_tag"

  get "/categories/new" => "categories#new", :as => "new_category"
  get "/categories/:category_name/edit" => "categories#edit", :as => "edit_category"
  get "/categories/:category" => "home#category", :as => :category
  post "/categories" => "categories#create"
  post "/categories/:category_name" => "categories#update", :as => "update_category"

  post "/invitations" => "invitations#create"
  get "/invitations" => "invitations#index"
  get "/invitations/request" => "invitations#build"
  post "/invitations/create_by_request" => "invitations#create_by_request",
    :as => "create_invitation_by_request"
  get "/invitations/confirm/:code" => "invitations#confirm_email"
  post "/invitations/send_for_request" => "invitations#send_for_request",
    :as => "send_invitation_for_request"
  get "/invitations/:invitation_code" => "signup#invited"
  post "/invitations/delete_request" => "invitations#delete_request",
    :as => "delete_invitation_request"

  resources :hat_requests, except: [:edit] do
    member do
      post :approve
      post :reject
    end
  end
  resources :hats, except: [:new, :update, :destroy] do
    member do
      get :doff
      post :doff_by_user
      post :update_in_place
      post :update_by_recreating
    end
  end

  get "/moderations" => "moderations#index"
  get "/moderations/page/:page" => "moderations#index"
  get "/moderators" => "users#tree", :moderators => true

  get "/mod" => "mod#index"
  get "/mod/flagged_stories/:period" => "mod#flagged_stories", :as => "mod_flagged_stories"
  get "/mod/flagged_comments/:period" => "mod#flagged_comments", :as => "mod_flagged_comments"
  get "/mod/commenters/:period" => "mod#commenters", :as => "mod_commenters"
  get "/mod/notes(/:period)" => "mod_notes#index", :as => "mod_notes"
  post "/mod/notes" => "mod_notes#create"

  namespace :mod do
    resources :reparents, only: [:new, :create]
    resources :stories, only: [:edit, :update] do
      patch "undelete"
      patch "destroy"
    end
  end

  mount MissionControl::Jobs::Engine, at: "/jobs"

  get "/privacy" => "about#privacy"
  get "/about" => "about#about"
  get "/chat" => "about#chat"

  get "/stats" => "stats#index"

benchmarks/lobsters/app/models/message.rb
# typed: false

class Message < ApplicationRecord
  belongs_to :recipient,
    class_name: "User",
    foreign_key: "recipient_user_id",
    inverse_of: :received_messages
  belongs_to :author,
    class_name: "User",
    foreign_key: "author_user_id",
    inverse_of: :sent_messages,
    optional: true
  belongs_to :hat,
    optional: true

  attribute :mod_note, :boolean
  attr_reader :recipient_username

  validates :subject, length: {in: 1..100}
  validates :body, length: {maximum: 70_000}, on: :update # for weird old data
  validates :body, length: {maximum: 8_192}, on: :create # for weird old data
  validates :short_id, length: {maximum: 30}
  validates :has_been_read, :deleted_by_author, :deleted_by_recipient, inclusion: {in: [true, false]}
  validate :hat do
    next if hat.blank?
    if author.blank? || author.wearable_hats.exclude?(hat)
      errors.add(:hat, "not wearable by author")
    end
  end

  scope :inbox, ->(user) {
    where(
      recipient: user,
      deleted_by_recipient: false
    ).preload(:author, :hat, :recipient).order("id asc")
  }
  scope :outbox, ->(user) {
    where(
      author: user,
      deleted_by_author: false
    ).preload(:author, :hat, :recipient).order("id asc")
  }
  scope :unread, -> { where(has_been_read: false, deleted_by_recipient: false) }

  before_validation :assign_short_id, on: :create
  after_create :deliver_email_notifications
  after_destroy :update_unread_counts
  after_save :update_unread_counts
  after_save :check_for_both_deleted

  def as_json(_options = {})
    attrs = [
      :short_id,
      :created_at,
      :has_been_read,
      :subject,
      :body,
      :deleted_by_author,
      :deleted_by_recipient
    ]

    h = super(only: attrs)

    h[:author_username] = author.try(:username)
    h[:recipient_username] = recipient.try(:username)

    h
  end

  def assign_short_id
    self.short_id = ShortId.new(self.class).generate
  end

  def author_username
    if author
      author.username
    else
      "System"
    end
  end

  def check_for_both_deleted
    if deleted_by_author? && deleted_by_recipient?
      destroy!
    end
  end

  def update_unread_counts
    recipient.update_unread_message_count!
  end

  def deliver_email_notifications
    if recipient.email_messages?
      begin
        EmailMessageMailer.notify(self, recipient).deliver_now
      rescue => e
        Rails.logger.error "error e-mailing #{recipient.email}: #{e}"
      end
    end

    return if Rails.env.development?

    if recipient.pushover_messages?
      recipient.pushover!(
        title: "#{Rails.application.name} message from " \
          "#{author_username}: #{subject}",
        message: plaintext_body,
        url: url,
        url_title: (author ? "Reply to #{author_username}" :
          "View message")
      )
    end
  end

  def recipient_username=(username)
    self.recipient_user_id = nil

    if (u = User.find_by(username: username))
      self.recipient_user_id = u.id
      @recipient_username = username
    else
      errors.add(:recipient_username, "is not a valid user")
    end
  end

  def linkified_body
    Markdowner.to_html(body)
  end

  def plaintext_body
    # TODO: linkify then strip tags and convert entities back
    body.to_s
  end

  def to_param
    short_id
  end

  def url
    Rails.application.root_url + "messages/#{short_id}"
  end
end

benchmarks/lobsters/app/controllers/messages_controller.rb
# typed: false

class MessagesController < ApplicationController
  before_action :require_logged_in_user
  before_action :require_logged_in_moderator, only: [:mod_note]
  before_action :find_message, only: [:show, :destroy, :keep_as_new, :mod_note]
  before_action :show_title_h1

  def index
    @title = "Private Messages"
    @messages = Message.inbox(@user).load

    respond_to do |format|
      format.html {
        @title = "Messages"

        @new_message = Message.new

        @direction = :in

        if params[:to]
          @new_message.recipient_username = params[:to]
        end
      }
      format.json {
        render json: @messages
      }
    end
  end

  def sent
    @title = "Sent Messages"
    @messages = Message.outbox(@user).load

    respond_to do |format|
      format.html {
        @title = "Messages Sent"

        @direction = :out

        @new_message = Message.new

        render action: "index"
      }
      format.json {
        render json: @messages
      }
    end
  end

  def create
    @title = "Messages"

    @new_message = Message.new(message_params)
    @new_message.author_user_id = @user.id
    @new_message.hat = @user.wearable_hats.find_by(short_id: params[:message][:hat_id])

    @direction = :out

    if @new_message.save
      if @user.is_moderator? && @new_message.mod_note
        ModNote.create_from_message(@new_message, @user)
      end
      flash[:success] = "Your message has been sent to #{@new_message.recipient.username}."
      redirect_to "/messages"
    else
      @messages = Message.inbox(@user).load
      render action: "index"
    end
  end

  def show
    @title = @message.subject

    if @message.author
      @new_message = Message.new
      @new_message.recipient_username = ((@message.author_user_id == @user.id) ?
        @message.recipient.username : @message.author.username)

      @new_message.subject = if /^re:/i.match?(@message.subject)
        @message.subject
      else
        "Re: #{@message.subject}"
      end
    end

    if @message.recipient_user_id == @user.id
      @message.has_been_read = true
      @message.save!
    end
    Rails.cache.delete("user:#{@user.id}:unread_replies")
  end

  def destroy
    if @message.author_user_id == @user.id
      @message.deleted_by_author = true
    end

    if @message.recipient_user_id == @user.id
      @message.deleted_by_recipient = true
    end

    @message.save!

    flash[:success] = "Deleted message."

    if @message.author_user_id == @user.id
      redirect_to "/messages/sent"
    else
      redirect_to "/messages"
    end
  end

  def batch_delete
    deleted = 0

    params.each do |k, v|
      if (v.to_s == "1") && (m = k.match(/^delete_(.+)$/))
        if (message = Message.where(short_id: m[1]).first)
          ok = false
          if message.author_user_id == @user.id
            message.deleted_by_author = true
            ok = true
          end
          if message.recipient_user_id == @user.id
            message.deleted_by_recipient = true
            ok = true
          end

          if ok
            message.save!
            deleted += 1
          end
        end
      end
    end

    flash[:success] = "Deleted #{deleted} #{"message".pluralize(deleted)}"

    @user.update_unread_message_count!

    redirect_to "/messages"
  end

  def keep_as_new
    @message.has_been_read = false
    @message.save!

    redirect_to "/messages"
  end

  def mod_note
    ModNote.create_from_message(@message, @user)

    redirect_to @message, notice: "ModNote created"
  end

  private

  def message_params
    params.require(:message).permit(
      :recipient_username, :subject, :body, :hat_id,
      @user.is_moderator? ? :mod_note : nil
    )
  end

  def find_message
    if (@message = Message.where(short_id: params[:message_id] || params[:id]).first)
      if @message.author_user_id == @user.id || @message.recipient_user_id == @user.id
        return true
      end
    end

    flash[:error] = "Could not find message."
    redirect_to "/messages"
    false
  end
end

benchmarks/lobsters/app/views/messages/_form.html.erb
<%# locals: (new_message:, replying:) -%>
<%= form_with model: new_message, url: new_message, method: :post do |f| %>
  <%= errors_for new_message %>

  <% if replying %>
      <%= f.hidden_field :recipient_username  %>
  <% else %>
    <div class="boxline">
      <%= f.label :recipient_username, "To:", :class => "required" %>
      <%= f.text_field :recipient_username, :size => 20 %>
    </div>
  <% end %>

  <div class="boxline">
    <%= f.label :subject, "Subject:", :class => "required" %>
    <%= f.text_field :subject, :style => "width: 500px;",
      :maxlength => 100 %>
  </div>

  <div class="boxline">
    <%= f.label :body, "Message:", :class => "required" %>
    <%= f.text_area :body, :style => "width: 500px;", :rows => 5 %>
  </div>

  <% if @user.wearable_hats.load.any? %>
    <div class="boxline">
      <%= f.label :hat_id, 'Put on hat:' %>
      <%= f.select :hat_id, options_for_select( [['','']] +
        @user.wearable_hats.map{|h| [h.hat, { 'data-modnote' => h.modlog_use }, h.short_id] }
      ) %>
      <% if @user.is_moderator? %>
        &nbsp;&nbsp;
        <%= f.check_box 'mod_note', class: 'normal' %>
        <%= f.label :mod_note, 'ModNote', class: 'normal' %>
      <% end %>
    </div>
  <% end %>

  <div class="boxline">
    <p></p>
    <%= f.submit replying ? "Reply" : "Send Message" %>
  </div>
<% end %>

benchmarks/lobsters/app/views/messages/_subnav.html.erb
<%# locals: () -%>
<% content_for :subnav do %>
  <%= link_to_different_page('Unread',   replies_unread_path) %>
  <%= link_to_different_page('All',      replies_path) %>
  <%= link_to_different_page('Comments', replies_comments_path) %>
  <%= link_to_different_page('Stories',  replies_stories_path) %>
  |
  <%= link_to_different_page 'Messages', messages_path %>
  <%= link_to_different_page 'Sent', messages_sent_path %>
<% end %>

benchmarks/lobsters/app/views/messages/index.html.erb
<%= render partial: 'subnav' %>

<div class="box wide">
  <% if @messages.any? %>
    <%= form_with url: batch_delete_messages_path do |f| %>
      <table class="data zebra with_select_all" width="100%" cellspacing=0>
      <tr>
        <th width="3%"></th>
        <th width="15%"><%= @direction == :in ? "From" : "To" %></th>
        <th width="17%"><%= @direction == :in ? "Received" : "Sent" %></th>
        <th width="60%">Subject</th>
      </tr>
      <% @messages.each do |message| %>
        <tr class="<%= message.has_been_read? ? "" : "bold" %>">
          <td><%= check_box_tag "delete_#{message.short_id}" %></td>
          <td>
            <div style="white-space:nowrap;">
              <% if @direction == :in %>
                <% if message.author %>
                  <%= styled_user_link message.author %>
                <% else %>
                  <%= message.author_username %>
                <% end %>
                <%= message.hat.to_html_label if message.hat %>
              <% else %>
                <%= styled_user_link message.recipient %>
              <% end %>
            </div>
          </td>
          <td><%= how_long_ago_label(message.created_at) %></td>
          <td><a href="/messages/<%= message.short_id %>"><%= message.subject
            %></a></td>
        </tr>
      <% end %>
      </table>
      <p>
      <%= f.submit "Delete Selected" %>
      </p>
    <% end %>
  <% else %>
    <p>
    You do not have any <%= @direction == :in ? "" : "sent" %> private
      messages.
    </p>
  <% end %>

  <br>

  <p>
    Compose Message
  </p>

  <%= render partial: 'form', locals: { new_message: @new_message, replying: false } %>
</div>

benchmarks/lobsters/app/views/messages/show.html.erb
<%= render partial: 'subnav' %>

<div class="box wide">
  <h2>
    From
    <% if @message.author %>
      <%= styled_user_link @message.author %>
    <% else %>
      <%= @message.author_username %>
    <% end %>
    <%= @message.hat.to_html_label if @message.hat %>
    to
    <%= styled_user_link @message.recipient %>
    <%= how_long_ago_label(@message.created_at) %>
  </h2>

  <div class="boxline comment_text">
    <%= raw @message.linkified_body %>
  </div>

  <br>

  <div class="boxline">
    <div style="float: left;">
      <%= form_with url: message_path(@message.short_id), method: :delete do |f| %>
        <%= f.submit "Delete Message" %>
      <% end %>
    </div>

    <div style="float: left; padding-left: 1em;">
      <%= form_with url: message_keep_as_new_path(@message.short_id), method: :post do |f| %>
        <%= f.submit "Keep As New" %>
      <% end %>
    </div>

    <% if @user.is_moderator? %>
      <div style="float: left; padding-left: 1em;">
        <%= form_with url: message_mod_note_path(@message.short_id), method: :post do |f| %>
          <%= f.submit "ModNote" %>
        <% end %>
      </div>
    <% end %>
  </div>

  <div style="clear: both;"></div>

  <br>

  <% if @new_message %>
    <p>
      Compose Reply
      <% if @new_message %>
        To <%= @new_message.recipient_username %>
      <% end %>
    </p>

    <%= render partial: 'form', locals: { new_message: @new_message, replying: true } %>
  <% else %>
    For help with this message, contact <%= link_to 'a moderator', moderators_path %>.
  <% end %>
</div>