benchmarks/lobsters/config/routes.rb
# typed: false

Rails.application.routes.draw do
  root to: "home#index",
    # protocol: (Rails.application.config.force_ssl ? "https://" : "http://"),
    as: "root"

  get "/404" => "about#four_oh_four", :via => :all

  get "/rss" => "home#index", :format => "rss"
  get "/hottest" => "home#index", :format => "json"

  get "/page/:page" => "home#index"

  get "/active" => "home#active"
  get "/active/page/:page" => "home#active"
  get "/newest" => "home#newest"
  get "/newest/page/:page" => "home#newest"
  get "/recent" => "home#recent"
  get "/recent/page/:page" => "home#recent"
  get "/hidden" => "home#hidden"
  get "/hidden/page/:page" => "home#hidden"

  get "/saved" => "home#saved"
  get "/saved/page/:page" => "home#saved"
  get "/upvoted/stories" => "home#upvoted"
  get "/upvoted/stories/page/:page" => "home#upvoted"
  get "/upvoted/comments" => "comments#upvoted"
  get "/upvoted/comments/page/:page" => "comments#upvoted"
  get "/upvoted", to: redirect("/upvoted/stories")
  get "/upvoted/page/:page", to: redirect("/upvoted/stories/page/%{page}")

  get "/top" => "home#top"
  get "/top/rss" => "home#top", :format => "rss"
  get "/top/page/:page" => "home#top"
  get "/top/:length" => "home#top"
  get "/top/:length/page/:page" => "home#top"

  get "/threads" => "comments#user_threads"

  get "/replies" => "replies#all"
  get "/replies/page/:page" => "replies#all"
  get "/replies/comments" => "replies#comments"
  get "/replies/comments/page/:page" => "replies#comments"
  get "/replies/stories" => "replies#stories"
  get "/replies/stories/page/:page" => "replies#stories"
  get "/replies/unread" => "replies#unread"
  get "/replies/unread/page/:page" => "replies#unread"

  get "/login" => "login#index"
  post "/login" => "login#login"
  post "/logout" => "login#logout"
  get "/login/2fa" => "login#twofa"
  post "/login/2fa_verify" => "login#twofa_verify", :as => "twofa_login"

  get "/signup" => "signup#index"
  post "/signup" => "signup#signup"
  get "/signup/invite" => "signup#invite"

  get "/login/forgot_password" => "login#forgot_password",
    :as => "forgot_password"
  post "/login/reset_password" => "login#reset_password",
    :as => "reset_password"
  match "/login/set_new_password" => "login#set_new_password",
    :as => "set_new_password", :via => [:get, :post]

  get "/t/:tag" => "home#single_tag", :as => "tag", :constraints => {tag: /[^,\.]+/}
  get "/t/:tag" => "home#multi_tag", :as => "multi_tag"
  get "/t/:tag/page/:page" => "home#tagged"

  constraints id: /([^\/]+?)(?=\.json|\.rss|$|\/)/ do
    get "/domain/:id(.:format)", to: redirect("/domains/%{id}")
    get "/domain/:id/page/:page", to: redirect("/domains/%{id}/page/%{page}")
    get "/domains/:id(.:format)" => "home#for_domain", :as => "domain"
    get "/domains/:id/page/:page" => "home#for_domain"
    get "/domains/:id/origins" => "origins#for_domain", :as => "domain_origins"

    resources :domains, only: [:create, :edit, :update]
    patch "/domains_ban/:id" => "domains_ban#update", :as => "ban_domain"
    post "/domains_ban/:id" => "domains_ban#create_and_ban", :as => "create_and_ban_domain"

    # below `resources` so that /edit isn't taken as an identifier
    get "/domains/:id/:author", to: redirect("/origins/%{id}/%{author}")
    get "/domain/:domain/:identifier(.:format)", to: redirect("/domains/%{domain}/%{identifier}")
    get "/domain/:domain/:identifier/page/:page", to: redirect("/domains/%{domain}/%{idetifier}/page/%{page}")
  end

  constraints identifier: /(.+)(?=\.json|\.rss|$|\/)/ do
    # resources :origin, only: [:show, :edit, :update]
    get "/origins/:identifier/edit(.:format)" => "origins#edit", :as => "edit_origin"
    patch "/origins/:identifier" => "origins#update", :as => "update_origin"
    get "/origins/:identifier(.:format)" => "home#for_origin", :as => "origin"
    # leaving out pagination because identifiers (eg 'github.com/alice') can include slashes
    # get "/origins/:identifier/page/:page" => "home#for_domain"
  end

  get "/search" => "search#index"
  get "/search/:q" => "search#index"

  get "/stories/url/all" => "story_urls#all"
  get "/stories/url/latest" => "story_urls#latest"

  resources :stories, except: [:index] do
    get "/stories/:short_id", to: redirect("/s/%{short_id}")
    post "upvote"
    post "flag"
    post "unvote"
    patch "destroy"
    patch "undelete"
    post "hide"
    post "unhide"
    post "save"
    post "unsave"
    post "disown"
    resources :suggestions, only: [:new, :create]

    # Mapping old routes to new routes. can be safely removed after the next deployment
    get "suggest", to: redirect("/stories/suggestions/new", status: 302)
    post "suggest", to: redirect("/stories/suggestions", status: 307)
  end
  post "/stories/fetch_url_attributes", format: "json"
  post "/stories/preview" => "stories#preview"
  post "/stories/check_url_dupe" => "stories#check_url_dupe"

  resources :comments, except: [:new, :destroy] do
    member do
      get "/comments/:id" => "comments#redirect_from_short_id"
      get "reply"
      post "upvote"
      post "flag"
      post "unvote"

      post "delete"
      post "undelete"
      post "disown"
    end
  end
  get "/comments/page/:page" => "comments#index"
  get "/comments" => "comments#index"

  get "/messages/sent" => "messages#sent"
  get "/messages" => "messages#index"
  post "/messages/batch_delete" => "messages#batch_delete",
    :as => "batch_delete_messages"
  resources :messages do
    post "keep_as_new"
    post "mod_note"
  end

  get "/inbox" => "inbox#index"

  get "/c/:id.json" => "comments#show_short_id", :format => "json"
  get "/c/:id" => "comments#redirect_from_short_id"

  # deprecated
  get "/s/:story_id/:title/comments/:id" => "comments#redirect_from_short_id"

  get "/s/:id/(:title)" => "stories#show"

  get "/users" => "users#tree", :as => "users_tree"
  get "/~:username" => "users#show", :as => "user"
  get "/~:username/standing" => "users#standing", :as => "user_standing"
  get "/~:user/stories(/page/:page)" => "home#newest_by_user", :as => "newest_by_user"
  get "/~:user/threads" => "comments#user_threads", :as => "user_threads"

  post "/~:username/ban" => "users#ban", :as => "user_ban"
  post "/~:username/unban" => "users#unban", :as => "user_unban"
  post "/~:username/disable_invitation" => "users#disable_invitation",
    :as => "user_disable_invite"
  post "/~:username/enable_invitation" => "users#enable_invitation",
    :as => "user_enable_invite"

  # 2023-07 redirect /u to /~username and /users (for tree)
  get "/u", to: redirect("/users", status: 301)
  get "/u/:username", to: redirect("/~%{username}", status: 301)
  # we don't do /@alice but easy mistake with comments autolinking @alice
  get "/@:username", to: redirect("/~%{username}", status: 301)
  get "/u/:username/standing", to: redirect("~%{username}/standing", status: 301)
  get "/newest/:user", to: redirect("~%{user}/stories", status: 301)
  get "/newest/:user(/page/:page)", to: redirect("~%{user}/stories/page/%{page}", status: 301)
  get "/threads/:user", to: redirect("~%{user}/threads", status: 301)

  get "/avatars/:username_size.png" => "avatars#show"
  post "/avatars/expire" => "avatars#expire"

  get "/settings" => "settings#index"
  post "/settings" => "settings#update"
  post "/settings/delete_account" => "settings#delete_account",
    :as => "delete_account"
  get "/settings/2fa" => "settings#twofa", :as => "twofa"
  post "/settings/2fa_auth" => "settings#twofa_auth", :as => "twofa_auth"
  get "/settings/2fa_enroll" => "settings#twofa_enroll",
    :as => "twofa_enroll"
  get "/settings/2fa_verify" => "settings#twofa_verify",
    :as => "twofa_verify"
  post "/settings/2fa_update" => "settings#twofa_update",
    :as => "twofa_update"
  post "/settings/pushover_auth" => "settings#pushover_auth"
  get "/settings/pushover_callback" => "settings#pushover_callback"
  get "/settings/mastodon_authentication" => "settings#mastodon_authentication"
  get "/settings/mastodon_auth" => "settings#mastodon_auth"
  get "/settings/mastodon_callback" => "settings#mastodon_callback"
  post "/settings/mastodon_disconnect" => "settings#mastodon_disconnect"
  get "/settings/github_auth" => "settings#github_auth"
  get "/settings/github_callback" => "settings#github_callback"
  post "/settings/github_disconnect" => "settings#github_disconnect"

  resources :keybase_proofs, only: [:new, :create, :destroy]
  get "/.well-known/keybase-proof-config" => "keybase_proofs#kbconfig", :as => "keybase_config"

  get "/filters" => "filters#index"
  post "/filters" => "filters#update"

  get "/tags" => "tags#index"
  get "/tags.json" => "tags#index", :format => "json"
  get "/tags/new" => "tags#new", :as => "new_tag"
  get "/tags/:tag_name/edit" => "tags#edit", :as => "edit_tag"
  post "/tags" => "tags#create"
  post "/tags/:tag_name" => "tags#update", :as => "update_tag"

  get "/categories/new" => "categories#new", :as => "new_category"
  get "/categories/:category_name/edit" => "categories#edit", :as => "edit_category"
  get "/categories/:category" => "home#category", :as => :category
  post "/categories" => "categories#create"
  post "/categories/:category_name" => "categories#update", :as => "update_category"

  post "/invitations" => "invitations#create"
  get "/invitations" => "invitations#index"
  get "/invitations/request" => "invitations#build"
  post "/invitations/create_by_request" => "invitations#create_by_request",
    :as => "create_invitation_by_request"
  get "/invitations/confirm/:code" => "invitations#confirm_email"
  post "/invitations/send_for_request" => "invitations#send_for_request",
    :as => "send_invitation_for_request"
  get "/invitations/:invitation_code" => "signup#invited"
  post "/invitations/delete_request" => "invitations#delete_request",
    :as => "delete_invitation_request"

  resources :hat_requests, except: [:edit] do
    member do
      post :approve
      post :reject
    end
  end

benchmarks/lobsters/app/views/layouts/application.html.erb
<!doctype html>
<html
  lang="en"
  class='color-scheme-<%= @user&.prefers_color_scheme || 'system' %>'
>
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <link rel="icon" sizes="144x144" type="image/png" href="/touch-icon-144.png">
  <link rel="apple-touch-icon" sizes="57x57" href="/touch-icon.png" />
  <link rel="apple-touch-icon" sizes="114x114" href="/touch-icon.png" />
  <link rel="apple-touch-icon" sizes="72x72" href="/touch-icon-144.png" />
  <link rel="apple-touch-icon" sizes="144x144" href="/touch-icon-144.png" />
  <link rel="search" type="application/opensearchdescription+xml" href="/opensearch.xml" title="Lobsters">
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="referrer" content="always" />
  <meta name="theme-color" content="#AC130D" />
  <meta name="story-flags" content="<%=  Vote::STORY_REASONS.to_json %>">
  <meta name="comment-flags" content="<%=  Vote::COMMENT_REASONS.to_json %>">

  <% if @meta_tags %>
    <% @meta_tags.each do |k,v| %>
      <meta name="<%= k %>" content="<%= v %>" />
    <% end %>
  <% end %>
  <link rel="shortcut icon" href="/favicon.ico" />
  <% if @short_url %>
    <link rev="canonical" rel="self alternate shorter shorturl shortlink"
      href="<%= @short_url %>" />
  <% end %>
  <title><%= @title.present? ? "#{@title} | " : "" %><%=
    Rails.application.name %></title>

  <%# Includes all stylesheet files in app/assets/stylesheets %>
  <%= stylesheet_link_tag :app %>
  
  <%= stylesheet_link_tag "tom-select", "data-turbo-track": "reload" %>
  <%= stylesheet_link_tag "TomSelect_remove_button", "data-turbo-track": "reload" %>
  

  <% if @user %>
    <%= javascript_importmap_tags %>
  <% end %>

  <%= csrf_meta_tags %>
  <% if @rss_link %>
    <link rel="alternate" type="application/rss+xml"
      title="<%= @rss_link[:title] %>" href="<%= @rss_link[:href] %>" />
  <% end %>
  <% if @comments_rss_link %>
    <link rel="alternate" type="application/rss+xml"
      title="<%= @comments_rss_link[:title] %>"
      href="<%= @comments_rss_link[:href] %>" />
  <% end %>
  <meta name="robots" content="noai, noimageai">
</head>
<body data-username='<%= @user.try(:username) %>'>
  <header id="nav">
    <a id="logo" style="<%= @traffic_style %>" href="/" title="<%= Rails.application.name %> (Current traffic: <%= @traffic_intensity.to_i %>%)"></a>
    <%= @traffic_novelty %>

    <div class="navholder">
      <nav class="links">
        <%= link_to_different_page 'Active', active_path %>
        <%= link_to_different_page 'Recent', recent_path %>
        <%= link_to_different_page 'Comments', comments_path %>

        <% if @user && @user.can_submit_stories? %>
          <%= link_to_different_page 'Submit', new_story_path %>
        <% end %>

        <%= link_to_different_page 'Search', search_path %>


        <% if @user %>
          <% if @user.inbox_count > 0 %>
            <%= link_to raw("Inbox&nbsp;<span class='inbox_unread'>#{@user.inbox_count}</span>"), inbox_path, class: 'inbox corner' %>
          <% else %>
            <%= link_to "Inbox", inbox_path, class: 'inbox corner' %>
          <% end %>

          <%= link_to_different_page 'Threads', threads_path %>
          <%= link_to_different_page 'Saved', saved_path %>
          <%= link_to_different_page raw("#{@user.username}&nbsp;<span class='karma'>(#{@user.karma})</span>"), settings_path %>
        <% else %>
          <%= link_to_different_page 'Login', login_path, class: 'corner' %>
        <% end %>
      </nav>
    </div>

    <nav class="corner">
      <% if @user %>
        <% if @user.inbox_count > 0 %>
          <%= link_to raw("&#9993;&nbsp;<span class='inbox_unread'>#{@user.inbox_count}</span>"), inbox_path, class: 'inbox' %>
        <% else %>
          <%= link_to raw("&#9993;"), inbox_path, class: 'inbox' %>
        <% end %>
      <% else %>
        <%= link_to 'Login', login_path, class: 'corner' %>
      <% end %>
    </nav>
  </header>

  <% if content_for? :subnav %>
    <header id="subnav">
      <%= yield :subnav %>
    </header>
  <% end %>

  <div id="inside">
    <% if @title.present? && @title_h1 %>
      <h1 class="<%= @title_class %>"><%= @title %></h1>
    <% end %>

    <% [ :error, :success, :notice ].each do |f| %>
      <% if flash[f].present? %>
        <div class="flash-<%= f %>"><%= flash[f] %></div>
      <% end %>
    <% end %>

    <%= yield %>
  </div>

  <footer>
    <%= link_to 'About', about_path %>
    <% if !@user && Rails.application.open_signups? %>
      <a href="/invitations/open">Join <%= Rails.application.name %></a>
    <% end %>
    <% if @user && @user.can_see_invitation_requests? &&
          (iqc = InvitationRequest.verified_count) > 0 %>
      <a href="/invitations">Invitation Queue (<%= iqc %>)</a>
    <% end %>
    <%= link_to 'Tags', tags_path %>
    <% if @user && @user.is_moderator? && (hrc = HatRequest.count) > 0 %>
      <%= link_to "#{hrc} Hat Requests", hat_requests_path, class: 'mod' %>
    <% end %>
    <%= link_to 'Filter', filters_path %>
    <%= link_to 'Moderation Log', moderations_path %>

  </footer>

  <% if Maxmind.uk?(request.remote_ip) || Rails.env.development? %>
    <br>
    <div id="uk-osa" class="flash-error">
      <p>
      <b>You appear to be in the UK.</b>
      Lobsters urgently needs your help.
      The risks of the UK Online Safety Act will require that Lobsters geoblock the UK on <b>March 16, 2025</b>.
      Please visit <a href="https://lobste.rs/s/ukosa1">this story</a> and help us avoid this.
      (<a href='https://db-ip.com'>IP Geolocation by DB-IP</a> <a href="https://db-ip.com/db/lite.php">Lite</a>)
      </p>
    </div>
  <% end %>
  <span id="iab-pcm-sdk"></span><span id="iab-autofill-sdk"></span>
</body>
</html>